language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'

install: "composer self-update && composer install"

script: "phpunit -c tests"

after_script:
  - vendor/bin/test-reporter --coverage-report=tests/logs/clover.xml
